# Path to your dotfile directory containing this config file (relative to $HOME). 
dotfiles_dir = "dotfiles"

[settings]
# An array of post install shell commands
#posthooks = [ "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'" ]


# Dotfiles template with their respective `source` template and `target` directories.
[settings.dots]

# A dot entry representing a symlink, `source` is relative to `dotfiles_dir`
# and `target` shall be relative to $HOME directory or absolute.

# Terminal
foot = { source = "terminals/foot", target = ".config/foot" }

# Shell and configs
fish = { source = "shell/fish", target = ".config/fish" }
starship = { source = "shell/starship", target = ".config/starship.toml" }

# CLI
bottom = { source = "cli/bottom", target = ".config/bottom" }

# Wayland
sway = { source = "wayland/sway", target = ".config/sway" }
waybar = { source = "wayland/waybar", target = ".config/waybar" }
mako = { source = "wayland/mako", target = ".config/mako" }
electron = { source = "wayland/electron", target = ".config/electron-flags.conf" }

# Multiplexer
tmux = { source = "multiplexer/tmux", target = ".tmux.conf" }

# File explorer
yazi = { source = "explorer/yazi", target = ".config/yazi" }

# USB
udiskie = { source = "usb/udiskie", target = ".config/udiskie" }

# XDG-DESKTOP-PORTAL
portal = { source = "xdg-desktop-portal/portals", target = ".config/xdg-desktop-portal/portals.conf" }

# Editors
nvim = { source = "editors/nvim", target = ".config/nvim" }

# Video 
mpv = { source = "video/mpv", target = ".config/mpv" }
