[manager]
append_keymap = [
    { on = ["u", "u"], run = "plugin restore", desc = "Restore last deleted files/folders" },
]

prepend_keymap = [
    { on = ["C"], run = "plugin ouch --args=zip", desc = "Compress with ouch" },
    { on = ["M", "m"], run = "plugin simple-mtpfs --args='select-then-mount --jump'", desc = "Select device to mount and jump to its mount point" },
    { on = ["M", "r"], run = "plugin simple-mtpfs --args=remount-current-cwd-device", desc = "Remount device under cwd" },
    { on = ["M", "u"], run = "plugin simple-mtpfs --args=select-then-unmount", desc = "Select device then unmount" },
    { on = ["g", "m"], run = "plugin simple-mtpfs --args=jump-to-device", desc = "Select device then jump to its mount point" },
    { on = ["`", "`"], run = "plugin simple-mtpfs --args=jump-back-prev-cwd", desc = "Jump back to the position before jumped to device" },
    { on = "<C-o>", run = "plugin open-with-cmd --args=block", desc = "Open with command in the terminal" },
    { on = "<C-O>", run = "plugin open-with-cmd", desc = "Open with command" },
    { on = "T", run = "plugin max-preview", desc = "Maximize or restore preview" },
    { on = "T", run = "plugin hide-preview", desc = "Hide or show preview" },
    { on = "<C-n>", run = """         shell 'ripdrag "$@" -x 2>/dev/null &' --confirm     """, desc = "" },
    { on = ["g", "i"], run = "plugin lazygit", desc = "run lazygit" },
]
