[plugin]
#prepend_fetchers = [
#    { id = "mime", if = "!(mime|dummy)", name = "*", run = "mime-ext", prio = "high" },
#]

prepend_previewers = [
    { name = "*.csv", run = "rich-preview"}, # for csv files
    { name = "*.md", run = "rich-preview" }, # for markdown (.md) files
    { name = "*.rst", run = "rich-preview"}, # for restructured text (.rst) files
    { name = "*.ipynb", run = "rich-preview"}, # for jupyter notebooks (.ipynb)
    { name = "*.json", run = "rich-preview"}, # for json (.json) files
	# Archive previewer
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/x-xz",            run = "ouch" },
]


[preview]
max_width = 1920
max_height = 1060
image_delay = 0
cache_dir = "$HOME/.local/share/yazi/"
image_filter = "lanczos3"
image_quality = 90
sixel_fraction = 10
